### ISSUE TITLE
website is down - http://www.navigatio.click/

### ISSUE THREAD

**Issue by grand-lotus-iroh** [vishnu45/Navigatio#1]
If you want, you can host this for free on one my dedicated servers. I really like what your doing and want you to succeed.

GLHF and happy Thursday brothaa

**Comment by vishnu45** [comment]
Hi Maggew, thank you so much for the offer. The website is currently down since I have terminated the EC2 instance for the time being. The main aim of my work was to learn several services and tools like AWS.
